### ISSUE TITLE
Bound method

### ISSUE THREAD

**Issue by mohae** [dgryski/go-xoroshiro#1]
I wanted to use this package but need a method that provides a bounded result.  Is this something you'd be interested in merging?  If so which method signature would be preferable?

```
Bound(bound uint64) uint64{}
```

or 

```
Int63n(bound int64) int64{}
```

**Comment by dgryski** [comment]
Xoro implements the `rand.Source` interface, so you can use that.

If you're going to implement this, please ut `Int63n` and ensure the result is unbiased.  (Don't just use `Next() % bound` ).

**Comment by dgryski** [comment]
Closed by https://github.com/dgryski/go-xoroshiro/pull/2
