### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by yurivish** [dgryski/go-xoroshiro#3]
Hi! I found out about this package via a [twitter thread](https://twitter.com/dgryski/status/727203222209855489) which mentioned putting it in the public domain. I'm thinking about using this code in a side project and it would be great if such a license could be added. Right now I don't see any license listed.

It seems [GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) makes it pretty easy, if you haven't changed your mind since the 2016 thread :)

Thanks for writing this in any case!

**Comment by dgryski** [comment]
Thanks!
